# Generated by Django 2.1.5 on 2019-08-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('classroom', models.CharField(max_length=100)),
                ('major_id', models.ManyToManyField(to='app2.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, '老师'), (2, '非老师')], db_index=True, default=1)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test_item',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=30)),
                ('test_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='最近修改时间')),
            ],
            options={
                'db_table': 'test_of_item',
                'ordering': ['test_id'],
            },
        ),
        migrations.AddField(
            model_name='major',
            name='t_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_m', to='app2.Teacher'),
        ),
    ]
