# Generated by Django 2.1.5 on 2019-01-17 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='t_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='t_m', to='app2.Teacher'),
        ),
    ]
