# Generated by Django 2.1.5 on 2019-02-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20190117_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '老师'), (2, '非老师')], db_index=True, default=1),
        ),
    ]
