"""
Django settings for utils project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os,sys
# 设置路径，使得“dj_study”这个路径可以被查询到
APP_BASE_PATH = os.path.abspath('..')
sys.path.append(APP_BASE_PATH)

from dj_study.utils.logs import *     # 导入log文件

# 缓存
CACHES = {
    "default": {
        # 注意：使用Memcached缓存之前，必须先下载Memcached服务
        # 'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 300,  # 缓存超时时间（默认300，None表示永不过期，0表示立即过期）
    }
}


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$gb98u*63bbz)oq7)a8p6rko!18g%7006c=hgxc(cr6xk*$tje'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
    'app2',
    'dj_study.view_CBV',
    'rest_framework',
    'django_filters',
]

MIDDLEWARE = [
    # 'django.middleware.cache.UpdateCacheMiddleware',      # 全站缓存——顶部
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',   # 全站缓存——尾部
]

ROOT_URLCONF = 'utils.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'utils.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dg_test',
        'USER': 'root',
        'PASSWORD': 'ysh7776...',
        'HOST':'localhost',
        'PORT':'3306',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'test',
#         'USER': 'postgres',
#         'PASSWORD': 'shining321',   #123456
#         'HOST':'127.0.0.1',
#         'PORT':'5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# restful配置全局认证
REST_FRAMEWORK = {
    # 认证
    "DEFAULT_AUTHENTICATION_CLASSES":['dj_study.view_CBV.rest_auth.auth.FirstAuthentication','dj_study.view_CBV.rest_auth.auth.Authentication',],
    "UNAUTHENTICATED_USER":None,     # 匿名登录时设置，  request.user = None
    # "UNAUTHENTICATED_USER":lambda :"这是一个匿名用户",   # 当需要返回匿名用户的值时，可利用函数设置。
    "UNAUTHENTICATED_TOKEN":None,    # 匿名登录时设置，  request.token = None

    # 权限
    "DEFAULT_PERMISSION_CLASSES":['dj_study.view_CBV.rest_auth.permission.SvipPermission'],

    # 节流
    "DEFAULT_THROTTLE_CLASSES":['dj_study.view_CBV.rest_auth.throttle.VisitThrottle'],

    # 配置限流次数  “3/m”表示一分钟访问3次，s表示秒，h表示小时，d表示天
    "DEFAULT_THROTTLE_RATES":{
        "Luffy":"3/m",
        "LuffyUser":"10/m",
    },
    # 版本
    "DEFAULT_VERSIONING_CLASS":"rest_framework.versioning.URLPathVersioning",  # 配置全局版本号获取方法
    "DEFAULT_VERSION":"v1",          # 默认版本
    "ALLOWED_VERSIONS":["v1","v2","v3"],  # 允许指定版本访问
    "VERSION_PARAM":"version",        # 默认获取版本的key值

    # 解析器
    "DEFAULT_PARSER_CLASSES":["rest_framework.parsers.JSONParser","rest_framework.parsers.FormParser"],
}