# Generated by Django 2.1.5 on 2019-08-19 09:15

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('selfid', models.CharField(max_length=77, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=77)),
                ('photo', models.ImageField(blank=True, upload_to=app1.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='SeaTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5)),
                ('iphone', models.CharField(max_length=20)),
            ],
        ),
    ]
